name: "schemactl"
version: "0.1.0.0"
github: "duijf/schemactl"
license: "MPL-2.0"
author: "Laurens Duijvesteijn"
maintainer: "schemactl@duijf.io"
copyright: "2019 Laurens Duijvesteijn"

extra-source-files:
- README.md

description: |
  Please see the README on GitHub at <https://github.com/duijf/schemactl>

dependencies:
- attoparsec
- aeson
- base >= 4.7 && < 5
- bytestring
- cryptonite
- mtl
- text

library:
  source-dirs: src

executables:
  schemactl:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - schemactl

tests:
  schemactl-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - schemactl
